version: '3'

services:
  group-supplier:
    build:
      context: .
    image: group-supplier
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - ./:/app